name: CD

on:
  # Triggers the workflow on push to main
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
	build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs npm dependencies
      - name: Install dependencies
        run: npm install
			
			#Builds the react app
			-name: Build React App
			 run: npm run build
				
			-name: Push new build to gh-pages 
       run: 
